mobs:register_mob("mobs:dirt_monster", {
	type = "monster",
	hp_min = 3,
	hp_max = 27,
	exp_min = 0,
	exp_max = 35,
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
	textures = {"mobs_dirt_monster.png"},
	visual_size = {x=3, y=2.6},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 1.25,
	run_velocity = 3.75,
	damage = 2,
	drops = {
		{name = "default:dirt",
		chance = 1,
		min = 3,
		max = 5,},
	},
	armor = 100,
	drawtype = "front",
	water_damage = 1,
	lava_damage = 5,
	light_damage = 2,
	on_rightclick = nil,
	attack_type = "dogfight",
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
	jump = true,
	sounds = {
		attack = "mob_attack",
		death = "mob_death",
	},
	step = 0.5,
	blood_amount=30,
	blood_offset=.25,
	blood_texture = "default_dirt.png",
})

mobs:register_mob("mobs:dirt_monster2", {
	type = "monster",
	hp_min = 3,
	hp_max = 27,
	exp_min = 0,
	exp_max = 35,
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
	textures = {"mobs_dirt_monster.png"},
	visual_size = {x=3, y=2.6},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 1.25,
	run_velocity = 3.75,
	damage = 2,
	drops = {
		{name = "default:dirt",
		chance = 1,
		min = 3,
		max = 5,},
	},
	armor = 100,
	drawtype = "front",
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
	jump = true,
	sounds = {
		attack = "mob_attack",
		death = "mob_death1",
	},
	step = 0.5,
	blood_amount=30,
	blood_offset=.25,
	blood_texture = "default_dirt.png",
})

mobs:register_spawn("mobs:dirt_monster", {"default:dirt_with_grass"}, 3, -1, 5000, 3, 31000)
mobs:register_spawn("mobs:dirt_monster2", {"mg:dirt_with_dry_grass"}, 20, -1, 3000, 4, 31000)
