mobs:register_mob("mobs:oerkki", {
	type = "monster",
	hp_min = 8,
	hp_max = 34,
	exp_min=1,
	exp_max=88,
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_oerkki.x",
	textures = {"mobs_oerkki.png"},
	visual_size = {x=5, y=5},
	makes_footstep_sound = false,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 3,
	damage = 4,
	drops = {},
	armor = 100,
	drawtype = "front",
	light_resistant = true,
	water_damage = 1,
	lava_damage = 1,
	light_damage = 0,
	attack_type = "dogfight",
	animation = {
		stand_start = 0,
		stand_end = 23,
		walk_start = 24,
		walk_end = 36,
		run_start = 37,
		run_end = 49,
		punch_start = 37,
		punch_end = 49,
		speed_normal = 15,
		speed_run = 15,
	},
	jump = true,
	sounds = { 
		random = "mobs_eerie",
		attack = "mobs_oerkki_attack"
	},
	step=0.5,
	blood_amount = 0,
	
})
mobs:register_spawn("mobs:oerkki", {"default:stone"}, 3, -1, 7000, 3, -10)
mobs:register_spawn("mobs:oerkki", {"default:stone"}, 3, -1, 2000, 3, -100)
