mobs:register_mob("mobs:snow_monster", {
	type = "monster",
	hp_min = 10,
	hp_max = 35,
	exp_min = 3,
	exp_max = 35,
	collisionbox = {-0.35,-1.0,-0.35, 0.35,0.8,0.35},
	visual = "mesh",
	mesh = "character.x",
	textures = {"mobs_snow_monster.png"},
	visual_size = {x=1, y=1},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 3,
	damage = 2,
	drops = { },
	armor = 100,
	drawtype = "front",
	water_damage = 1,
	lava_damage = 5,
	light_damage = 2,
	on_rightclick = nil,
	attack_type = "dogfight",
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 200,
		punch_end = 219,
	},
	jump = true,
	sounds = {
		death = "mobs_yeti_death",
		random = "mobs_howl",
		attack = "mobs_slash_attack",
	},
	step = 0.5,
})
mobs:register_spawn("mobs:snow_monster", {"default:snow","default:snow_with_grass"}, 10, -1, 7000, 2, 31000)
